# rulebooks/print-from-eventstream.yml
- name: print alerts coming from Event Stream
  hosts: localhost

  # Placeholder so the Event Stream can be mapped to a source
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    # Print the whole event as a string (no custom filters)
#    - name: print raw event
#      condition: event.payload is defined or event.alerts is defined
#      action:
#        debug:
#          msg: "RAW EVENT: {{ event }}"

    # If Alertmanager payload is under payload.alerts
    - name: print each alert under payload.alerts
      condition: event.payload is defined and event.payload.alerts is defined
      action:
        debug:
          msg: |
            {% for a in event.payload.alerts %}
            [ALERT {{ loop.index }}]
            status:      {{ a.status | default('') }}
            alertname:   {{ a.labels.alertname | default('') }}
            severity:    {{ a.labels.severity | default('') }}
            namespace:   {{ a.labels.namespace | default('') }}
            instance:    {{ a.labels.instance | default('') }}
            startsAt:    {{ a.startsAt | default('') }}
            endsAt:      {{ a.endsAt | default('') }}
            summary:     {{ a.annotations.summary | default('') }}
            description: {{ a.annotations.description | default('') }}
            labels:      {{ a.labels | default({}) }}
            annotations: {{ a.annotations | default({}) }}
            -----
            {% endfor %}

    # If alerts[] is top-level
#    - name: print each alert when top-level alerts exists
#      condition: event.alerts is defined
#      action:
#        debug:
#          msg: |
#            {% for a in event.alerts %}
#            [ALERT {{ loop.index }}]
#            status:      {{ a.status | default('') }}
#            alertname:   {{ a.labels.alertname | default('') }}
#            severity:    {{ a.labels.severity | default('') }}
#            namespace:   {{ a.labels.namespace | default('') }}
#            instance:    {{ a.labels.instance | default('') }}
#            startsAt:    {{ a.startsAt | default('') }}
#            endsAt:      {{ a.endsAt | default('') }}
#            summary:     {{ a.annotations.summary | default('') }}
#            description: {{ a.annotations.description | default('') }}
#            labels:      {{ a.labels | default({}) }}
#            annotations: {{ a.annotations | default({}) }}
#            -----
#            {% endfor %}
