---
- name: Handle Alertmanager alerts from EDA
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: alerts
      prompt: ""
      private: false

  tasks:
    - name: Quick summary
      debug:
        msg: "{{ alerts }}"
