---
- name: Handle Alertmanager alerts from EDA
  hosts: localhost
  gather_facts: false

  vars:
    payload: "{{ ansible_eda.event.payload }}"
    alerts: "{{ ansible_eda.event.payload.alerts }}"

  tasks:
    - name: Quick summary
      debug:
        msg: "{{ alerts }}"
