---
- name: Handle Alertmanager alerts from EDA
  hosts: localhost
  gather_facts: false

  vars:
    alerts: "{{ alerts }}"
    payload: "{{ payload }}"

  tasks:
    - name: Quick summary
      debug:
        msg: "{{ alerts }}"
