---
- name: Print Alerts and Payload from EDA
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Print the 'alerts' variable
      ansible.builtin.debug:
        msg: "Received 'alerts' data: {{ alerts }}"
      when: alerts is defined

    - name: Print the full 'payload' variable
      ansible.builtin.debug:
        msg: "Received 'payload' data: {{ payload }}"
      when: payload is defined

    - name: Print the full 'namespace' variable
      ansible.builtin.debug:
        msg: "Received 'namespace' data: {{ namespace }}"
      when: namespace is defined

    - name: Print the full 'summary' variable
      ansible.builtin.debug:
        msg: "Received 'summary' data: {{ summary }}"
      when: summary is defined

    - name: Print the full 'description' variable
      ansible.builtin.debug:
        msg: "Received 'description' data: {{ description }}"
      when: description is defined



