---
- name: Handle Alertmanager alerts from EDA
  hosts: localhost
  gather_facts: false

  vars:
    alerts: "{{ ansible_eda.event.payload.alerts }}"
    payload: "{{ ansible_eda.event.payload }}"

  tasks:
    - name: Dump all received variables
      debug:
        var: vars

    - name: Print each alert (if any)
      when: alerts_effective is iterable and (alerts_effective | length) > 0
      loop: "{{ alerts }}"
      loop_control:
        label: "{{ (item.labels.alertname | default('unknown')) ~ ' (' ~ (item.status | default('')) ~ ')' }}"
      debug:
        msg: |
          [ALERT]
          status:      {{ item.status | default('') }}
          alertname:   {{ item.labels.alertname | default('') }}
          severity:    {{ item.labels.severity | default('') }}
          namespace:   {{ item.labels.namespace | default('') }}
          instance:    {{ item.labels.instance | default('') }}
          startsAt:    {{ item.startsAt | default('') }}
          endsAt:      {{ item.endsAt | default('') }}
          summary:     {{ item.annotations.summary | default('') }}
          description: {{ item.annotations.description | default('') }}
          labels:      {{ item.labels | default({}) }}
          annotations: {{ item.annotations | default({}) }}
